/*
 * Copyright (C) 2020 Antoine CORDIER
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *         http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { SelectOptions } from "../types/select-option";

export const PresetOptions = new SelectOptions([
  {
    name: "INIT",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 0 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 63 },
        sustain: { value: 80 },
        release: { value: 20 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 127 },
        resonance: { value: 0 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 0 },
        amount: { value: 0 },
        velocity: { value: 0 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "THICK PAD",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 58 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 69 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 64 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 60 },
        decay: { value: 40 },
        sustain: { value: 100 },
        release: { value: 60 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 80 },
        resonance: { value: 20 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 30 },
        decay: { value: 60 },
        amount: { value: 40 },
        velocity: { value: 20 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 2 },
        frequency: { value: 8 },
        modAmount: { value: 10 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 5 },
        frequency: { value: 5 },
        modAmount: { value: 8 },
      },
    },
  },
  {
    name: "ACID BASS",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 30 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 30 },
        sustain: { value: 0 },
        release: { value: 5 },
      },
      filter: {
        mode: { value: 1 },
        cutoff: { value: 10 },
        resonance: { value: 100 },
        drive: { value: 50 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 25 },
        amount: { value: 80 },
        velocity: { value: 50 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "PLUCK",
    value: {
      osc1: {
        mode: { value: 3 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 95.25 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 40 },
      noiseLevel: { value: 5 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 50 },
        sustain: { value: 0 },
        release: { value: 15 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 40 },
        resonance: { value: 30 },
        drive: { value: 10 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 30 },
        amount: { value: 60 },
        velocity: { value: 40 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "STRINGS",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 66 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 60 },
      noiseLevel: { value: 3 },
      envelope: {
        attack: { value: 80 },
        decay: { value: 30 },
        sustain: { value: 90 },
        release: { value: 70 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 70 },
        resonance: { value: 10 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 50 },
        decay: { value: 40 },
        amount: { value: 20 },
        velocity: { value: 10 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 0 },
        frequency: { value: 10 },
        modAmount: { value: 4 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 2 },
        frequency: { value: 6 },
        modAmount: { value: 6 },
      },
    },
  },
  {
    name: "WOBBLE",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 31.75 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 31.75 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 50 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 0 },
        sustain: { value: 127 },
        release: { value: 10 },
      },
      filter: {
        mode: { value: 1 },
        cutoff: { value: 30 },
        resonance: { value: 80 },
        drive: { value: 40 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 0 },
        amount: { value: 0 },
        velocity: { value: 0 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 2 },
        frequency: { value: 20 },
        modAmount: { value: 90 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "BRASS",
    value: {
      osc1: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 75 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 45 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 5 },
        decay: { value: 40 },
        sustain: { value: 70 },
        release: { value: 15 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 50 },
        resonance: { value: 15 },
        drive: { value: 20 },
      },
      cutoffMod: {
        attack: { value: 3 },
        decay: { value: 30 },
        amount: { value: 60 },
        velocity: { value: 40 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "AMBIENT",
    value: {
      osc1: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 3 },
        semiShift: { value: 95.25 },
        centShift: { value: 66 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 35 },
      noiseLevel: { value: 8 },
      envelope: {
        attack: { value: 100 },
        decay: { value: 50 },
        sustain: { value: 80 },
        release: { value: 100 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 60 },
        resonance: { value: 25 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 60 },
        decay: { value: 80 },
        amount: { value: 30 },
        velocity: { value: 10 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 2 },
        frequency: { value: 4 },
        modAmount: { value: 15 },
      },
      lfo2: {
        mode: { value: 3 },
        destination: { value: 5 },
        frequency: { value: 3 },
        modAmount: { value: 10 },
      },
    },
  },
  {
    name: "SUB BASS",
    value: {
      osc1: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 0 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 2 },
        decay: { value: 20 },
        sustain: { value: 100 },
        release: { value: 10 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 50 },
        resonance: { value: 0 },
        drive: { value: 15 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 15 },
        amount: { value: 20 },
        velocity: { value: 30 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "RESO LEAD",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 67 },
        cycle: { value: 50 },
      },
      osc2Amplitude: { value: 55 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 10 },
        sustain: { value: 110 },
        release: { value: 15 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 60 },
        resonance: { value: 70 },
        drive: { value: 25 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 20 },
        amount: { value: 40 },
        velocity: { value: 50 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 0 },
        frequency: { value: 35 },
        modAmount: { value: 5 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "FUNK BASS",
    value: {
      osc1: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 55 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 25 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 25 },
        sustain: { value: 50 },
        release: { value: 8 },
      },
      filter: {
        mode: { value: 1 },
        cutoff: { value: 18 },
        resonance: { value: 75 },
        drive: { value: 45 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 18 },
        amount: { value: 80 },
        velocity: { value: 55 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 2 },
        frequency: { value: 15 },
        modAmount: { value: 25 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "SYNC LEAD",
    value: {
      osc1: {
        mode: { value: 1 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 1 },
        semiShift: { value: 83 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 70 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 15 },
        sustain: { value: 100 },
        release: { value: 12 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 90 },
        resonance: { value: 35 },
        drive: { value: 15 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 25 },
        amount: { value: 35 },
        velocity: { value: 40 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 0 },
        frequency: { value: 40 },
        modAmount: { value: 4 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "ELECTRIC PIANO",
    value: {
      osc1: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 3 },
        semiShift: { value: 95.25 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 30 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 60 },
        sustain: { value: 30 },
        release: { value: 35 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 75 },
        resonance: { value: 10 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 40 },
        amount: { value: 25 },
        velocity: { value: 55 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 0 },
        frequency: { value: 25 },
        modAmount: { value: 3 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "CLAV",
    value: {
      osc1: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 45 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 80 },
      },
      osc2Amplitude: { value: 35 },
      noiseLevel: { value: 3 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 35 },
        sustain: { value: 0 },
        release: { value: 5 },
      },
      filter: {
        mode: { value: 2 },
        cutoff: { value: 50 },
        resonance: { value: 55 },
        drive: { value: 25 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 20 },
        amount: { value: 55 },
        velocity: { value: 65 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "NOISE SWEEP",
    value: {
      osc1: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 0 },
      noiseLevel: { value: 90 },
      envelope: {
        attack: { value: 50 },
        decay: { value: 40 },
        sustain: { value: 80 },
        release: { value: 80 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 20 },
        resonance: { value: 85 },
        drive: { value: 10 },
      },
      cutoffMod: {
        attack: { value: 70 },
        decay: { value: 50 },
        amount: { value: 60 },
        velocity: { value: 20 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 2 },
        frequency: { value: 6 },
        modAmount: { value: 50 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 3 },
        frequency: { value: 4 },
        modAmount: { value: 20 },
      },
    },
  },
  {
    name: "RING MOD",
    value: {
      osc1: {
        mode: { value: 0 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 0 },
        semiShift: { value: 82 },
        centShift: { value: 80 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 80 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 70 },
        sustain: { value: 20 },
        release: { value: 50 },
      },
      filter: {
        mode: { value: 2 },
        cutoff: { value: 45 },
        resonance: { value: 50 },
        drive: { value: 15 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 50 },
        amount: { value: 30 },
        velocity: { value: 30 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 3 },
        destination: { value: 1 },
        frequency: { value: 8 },
        modAmount: { value: 15 },
      },
    },
  },
  {
    name: "CHIPTUNE",
    value: {
      osc1: {
        mode: { value: 2 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 2 },
        semiShift: { value: 95.25 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 40 },
      noiseLevel: { value: 0 },
      envelope: {
        attack: { value: 0 },
        decay: { value: 0 },
        sustain: { value: 127 },
        release: { value: 3 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 127 },
        resonance: { value: 0 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 0 },
        decay: { value: 0 },
        amount: { value: 0 },
        velocity: { value: 0 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 0 },
        frequency: { value: 0 },
        modAmount: { value: 0 },
      },
    },
  },
  {
    name: "DARK PAD",
    value: {
      osc1: {
        mode: { value: 3 },
        semiShift: { value: 63.5 },
        centShift: { value: 61 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 3 },
        semiShift: { value: 63.5 },
        centShift: { value: 66 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 60 },
      noiseLevel: { value: 5 },
      envelope: {
        attack: { value: 90 },
        decay: { value: 50 },
        sustain: { value: 100 },
        release: { value: 90 },
      },
      filter: {
        mode: { value: 0 },
        cutoff: { value: 35 },
        resonance: { value: 20 },
        drive: { value: 10 },
      },
      cutoffMod: {
        attack: { value: 70 },
        decay: { value: 60 },
        amount: { value: 15 },
        velocity: { value: 10 },
      },
      lfo1: {
        mode: { value: 0 },
        destination: { value: 2 },
        frequency: { value: 3 },
        modAmount: { value: 10 },
      },
      lfo2: {
        mode: { value: 3 },
        destination: { value: 1 },
        frequency: { value: 2 },
        modAmount: { value: 8 },
      },
    },
  },
  {
    name: "SHIMMER",
    value: {
      osc1: {
        mode: { value: 3 },
        semiShift: { value: 63.5 },
        centShift: { value: 63.5 },
        cycle: { value: 63.5 },
      },
      osc2: {
        mode: { value: 0 },
        semiShift: { value: 95.25 },
        centShift: { value: 65 },
        cycle: { value: 63.5 },
      },
      osc2Amplitude: { value: 50 },
      noiseLevel: { value: 6 },
      envelope: {
        attack: { value: 70 },
        decay: { value: 40 },
        sustain: { value: 85 },
        release: { value: 110 },
      },
      filter: {
        mode: { value: 3 },
        cutoff: { value: 50 },
        resonance: { value: 30 },
        drive: { value: 0 },
      },
      cutoffMod: {
        attack: { value: 40 },
        decay: { value: 60 },
        amount: { value: 25 },
        velocity: { value: 15 },
      },
      lfo1: {
        mode: { value: 3 },
        destination: { value: 2 },
        frequency: { value: 5 },
        modAmount: { value: 12 },
      },
      lfo2: {
        mode: { value: 0 },
        destination: { value: 4 },
        frequency: { value: 7 },
        modAmount: { value: 8 },
      },
    },
  },
]);
